# Generated by Django 5.0.6 on 2024-07-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_mail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
